# Generated by Django 5.0.3 on 2024-04-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Pounds'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='GBP', max_length=3),
        ),
    ]
